name: student-labs

services:
  frontend:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./app/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/frontend:/var/www/html

  web:
    image: python
    restart: always
    depends_on:
      - db
    command: sh -c "pip install -r requirement.txt && flask --app app run --host=0.0.0.0 --port=5002 --debug"
    network_mode: "host"
    volumes:
      - ./app:/app
    working_dir: /app

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mvp
    ports:
      - "127.0.0.1:8889:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "127.0.0.1:8080:80"
    environment:
      PMA_HOST: db

volumes:
  db_data:

